# Generated by Django 6.0.5 on 2026-06-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_storage_path_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AddField(
            model_name='user',
            name='storage_limit',
            field=models.BigIntegerField(default=1073741824),
        ),
        migrations.AddField(
            model_name='user',
            name='storage_used',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='file',
            name='last_download_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='share_link',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='unique_name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
